package com.jrds.pojo;

public class Dic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic.DIC_TYPE
     *
     * @mbggenerated
     */
    private String dicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic.DIC_EN
     *
     * @mbggenerated
     */
    private String dicEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic.DIC_CN
     *
     * @mbggenerated
     */
    private String dicCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic.DIC_NOTE
     *
     * @mbggenerated
     */
    private String dicNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic.ID
     *
     * @return the value of s_dic.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic.ID
     *
     * @param id the value for s_dic.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic.DIC_TYPE
     *
     * @return the value of s_dic.DIC_TYPE
     *
     * @mbggenerated
     */
    public String getDicType() {
        return dicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic.DIC_TYPE
     *
     * @param dicType the value for s_dic.DIC_TYPE
     *
     * @mbggenerated
     */
    public void setDicType(String dicType) {
        this.dicType = dicType == null ? null : dicType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic.DIC_EN
     *
     * @return the value of s_dic.DIC_EN
     *
     * @mbggenerated
     */
    public String getDicEn() {
        return dicEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic.DIC_EN
     *
     * @param dicEn the value for s_dic.DIC_EN
     *
     * @mbggenerated
     */
    public void setDicEn(String dicEn) {
        this.dicEn = dicEn == null ? null : dicEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic.DIC_CN
     *
     * @return the value of s_dic.DIC_CN
     *
     * @mbggenerated
     */
    public String getDicCn() {
        return dicCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic.DIC_CN
     *
     * @param dicCn the value for s_dic.DIC_CN
     *
     * @mbggenerated
     */
    public void setDicCn(String dicCn) {
        this.dicCn = dicCn == null ? null : dicCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic.DIC_NOTE
     *
     * @return the value of s_dic.DIC_NOTE
     *
     * @mbggenerated
     */
    public String getDicNote() {
        return dicNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic.DIC_NOTE
     *
     * @param dicNote the value for s_dic.DIC_NOTE
     *
     * @mbggenerated
     */
    public void setDicNote(String dicNote) {
        this.dicNote = dicNote == null ? null : dicNote.trim();
    }
}